/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/animals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Animals
         * @description List animals with pagination.
         */
        get: operations["list_animals_api_v1_animals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animals/{animal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Animal
         * @description Get animal detail with notes, kennel card, and assessments.
         */
        get: operations["get_animal_api_v1_animals__animal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint. Verifies database connectivity.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnimalDetailResponse
         * @description Full animal detail with related data.
         */
        AnimalDetailResponse: {
            animal: components["schemas"]["AnimalResponse"];
            kennel_card?: components["schemas"]["KennelCardResponse"] | null;
            /** Staff Assessments */
            staff_assessments: components["schemas"]["StaffAssessmentResponse"][];
            /** Volunteer Notes */
            volunteer_notes: components["schemas"]["VolunteerNoteResponse"][];
        };
        /**
         * AnimalListResponse
         * @description Paginated animal list.
         */
        AnimalListResponse: {
            /** Animals */
            animals: components["schemas"]["AnimalResponse"][];
            /** Count */
            count: number;
        };
        /**
         * AnimalResponse
         * @description Animal summary for list views.
         */
        AnimalResponse: {
            /** Age Years */
            age_years?: number | null;
            /** Aka */
            aka?: string | null;
            /** Behavior Mod Tags */
            behavior_mod_tags?: string[] | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Breed */
            breed?: string | null;
            /** Color Category */
            color_category?: string | null;
            /** Days In Shelter */
            days_in_shelter?: number | null;
            /** Id */
            id: string;
            /** Intake Date */
            intake_date?: string | null;
            /** Is Adoptable */
            is_adoptable?: boolean | null;
            /** Is Foster Care */
            is_foster_care?: boolean | null;
            /** Is In Kennel */
            is_in_kennel?: boolean | null;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Public Profile Url */
            public_profile_url?: string | null;
            /** Species */
            species?: string | null;
            /** Synced At */
            synced_at?: string | null;
            /** Weight Lbs */
            weight_lbs?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "connected" | "unavailable";
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * KennelCardResponse
         * @description Kennel card information.
         */
        KennelCardResponse: {
            /** About Text */
            about_text?: string | null;
            /** Animal Id */
            animal_id: string;
            /** Cats Compatibility */
            cats_compatibility?: string | null;
            /** Commands Known */
            commands_known?: string | null;
            /** Dogs Compatibility */
            dogs_compatibility?: string | null;
            /** Housebreaking Status */
            housebreaking_status?: string | null;
            /** Id */
            id?: number | null;
            /** Kids Compatibility */
            kids_compatibility?: string | null;
            /** Things Dislikes */
            things_dislikes?: string | null;
            /** Things Likes */
            things_likes?: string | null;
        };
        /**
         * StaffAssessmentResponse
         * @description Staff behavioral assessment.
         */
        StaffAssessmentResponse: {
            /** Animal Id */
            animal_id: string;
            /** Assessment Tags */
            assessment_tags?: string[] | null;
            /** Id */
            id?: number | null;
            /** Notes */
            notes?: string | null;
            /** Recorded At */
            recorded_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VolunteerNoteResponse
         * @description Volunteer behavioral observation.
         */
        VolunteerNoteResponse: {
            /** Animal Id */
            animal_id: string;
            /** Id */
            id?: number | null;
            /** Note Date */
            note_date: string;
            /** Note Text */
            note_text?: string | null;
            /** Rating Jumpy Mouthy */
            rating_jumpy_mouthy?: number | null;
            /** Rating Leash Reactivity */
            rating_leash_reactivity?: number | null;
            /** Rating Shy Fearful */
            rating_shy_fearful?: number | null;
            /** Rating Strong On Leash */
            rating_strong_on_leash?: number | null;
            /** Volunteer Name */
            volunteer_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_animals_api_v1_animals_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_animal_api_v1_animals__animal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
