/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Answer a question using RAG with conversation history.
         *
         *     Loads recent conversation history, runs the RAG pipeline, and
         *     persists both the user question and assistant response.
         */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List all documents for the current tenant.
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload and index a document (admin only).
         *
         *     Accepts a multipart file upload, validates the file, indexes it
         *     into the vector store, and creates a database record.
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Get a single document by ID.
         */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete a document and its indexed chunks (admin only).
         */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Return recent conversation history for the authenticated user.
         */
        get: operations["get_history_api_v1_history_get"];
        put?: never;
        post?: never;
        /**
         * Clear History
         * @description Clear all conversation history for the authenticated user.
         */
        delete: operations["clear_history_api_v1_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         *
         *     Checks database connectivity and pgvector extension availability.
         *     Never raises — returns degraded status on failure.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Request body for the ask endpoint.
         */
        AskRequest: {
            /** Question */
            question: string;
        };
        /**
         * AskResponse
         * @description Response from the RAG ask endpoint.
         */
        AskResponse: {
            /** Answer */
            answer: string;
            /**
             * Blocked
             * @default false
             */
            blocked: boolean;
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Chunks Used */
            chunks_used: components["schemas"]["ChunkWithScore"][];
            /** Confidence Level */
            confidence_level: string;
            /** Confidence Score */
            confidence_score: number;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /**
         * ChunkWithScore
         * @description A retrieved chunk with its similarity score.
         */
        ChunkWithScore: {
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Section */
            section: string;
            /** Source */
            source: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * ClearHistoryResponse
         * @description Result of clearing conversation history.
         */
        ClearHistoryResponse: {
            /** Deleted Count */
            deleted_count: number;
            /** Message */
            message: string;
        };
        /**
         * DocumentDeleteResponse
         * @description Result of deleting a document.
         */
        DocumentDeleteResponse: {
            /** Message */
            message: string;
        };
        /**
         * DocumentListResponse
         * @description List of documents with total count.
         */
        DocumentListResponse: {
            /** Count */
            count: number;
            /** Documents */
            documents: components["schemas"]["DocumentResponse"][];
        };
        /**
         * DocumentResponse
         * @description Single document metadata.
         */
        DocumentResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** File Size Bytes */
            file_size_bytes: number;
            /** File Type */
            file_type: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Indexed */
            is_indexed: boolean;
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
            /** Title */
            title: string;
        };
        /**
         * DocumentUploadResponse
         * @description Result of uploading and indexing a document.
         */
        DocumentUploadResponse: {
            /** Chunks Created */
            chunks_created: number;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message */
            message: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "connected" | "unavailable";
            /**
             * Moderation
             * @enum {string}
             */
            moderation: "gateway_guardrails" | "openai_api" | "disabled";
            /**
             * Pgvector
             * @enum {string}
             */
            pgvector: "available" | "unavailable";
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * MessageHistoryResponse
         * @description Paginated conversation history.
         */
        MessageHistoryResponse: {
            /** Count */
            count: number;
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
        };
        /**
         * MessageResponse
         * @description Single message in a conversation.
         */
        MessageResponse: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageHistoryResponse"];
                };
            };
        };
    };
    clear_history_api_v1_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearHistoryResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
